export const FETCH_WORK_START = 'FETCH_WORK_START';
export const FETCH_WORK_SUCCESS = 'FETCH_WORK_SUCCESS';
export const FETCH_WORK_FAIL = 'FETCH_WORK_FAIL';

export const FILTER_WORK_START = 'FILTER_WORK_START';
export const FILTER_WORK_SUCCESS = 'FILTER_WORK_SUCCESS';

export const CONTACT_DATA_START = 'CONTACT_DATA_START';
export const CONTACT_DATA_SUCCESS = 'CONTACT_DATA_SUCCESS';
export const CONTACT_DATA_FAIL = 'CONTACT_DATA_FAIL';
export const CONTACT_DATA_INIT = 'CONTACT_DATA_INIT';
